/* Core */
import { createSlice, type PayloadAction } from '@reduxjs/toolkit'
import type Office from '@/app/types/OfficeType'

/* Instruments */
import { getAllOfficesInfoAsync } from './thunkActions'

const initialState: OfficeSliceState = {
    value: [] as Office[],
    status: 'idle',
}

export const officeSlice = createSlice({
    name: 'office',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(getAllOfficesInfoAsync.pending, (state) => {
                state.status = 'loading'
            })
            .addCase(getAllOfficesInfoAsync.fulfilled, (state, action: PayloadAction<Office[]>) => {
                state.status = 'idle'
                state.value = action.payload
            })
    },
})

/* Types */
export interface OfficeSliceState {
    value: Office[]
    status: 'idle' | 'loading' | 'failed'
}
