/* Components */
import Banner from './components/Banner/Banner';
import Services from './components/Services/Services';
import Navbarin from './components/Navbar';
import Footer from './components/Footer/Footer'

export default function IndexPage() {
  return (
    <div>
      <Navbarin />
      <Banner />
      <Services />
      <Footer />
    </div>
  )
}

export const metadata = {
  title: 'Magic Post',
  description: 'Generated by create next app',
}
