/* Core */
import { createSlice, type PayloadAction } from '@reduxjs/toolkit'
import type Parcel from '@/app/types/ParcelType'

/* Instruments */
import { getAllParcelsInfoAsync } from './thunkActions'

const initialState: ParcelSliceState = {
    value: [] as Parcel[],
    status: 'idle',
}

export const parcelSlice = createSlice({
    name: 'parcel',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(getAllParcelsInfoAsync.pending, (state) => {
                state.status = 'loading'
            })
            .addCase(getAllParcelsInfoAsync.fulfilled, (state, action: PayloadAction<Parcel[]>) => {
                state.status = 'idle'
                state.value = action.payload
            })
    },
})

/* Types */
export interface ParcelSliceState {
    value: Parcel[]
    status: 'idle' | 'loading' | 'failed'
}
